services:
  # Backend Service
  - type: web
    name: schoolplatform-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - fromGroup: schoolplatform-secrets

  # Frontend Service  
  - type: web
    name: schoolplatform-frontend
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview
    staticPublishPath: ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
      - fromGroup: schoolplatform-secrets

# Environment Groups
envGroups:
  - name: schoolplatform-secrets
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: PG_HOST
        sync: false
      - key: PG_DATABASE
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
