#!/bin/bash

echo "🔍 Supabase Connection String Helper"
echo "===================================="
echo ""
echo "Since DNS lookup is failing for your project hostname, please follow these steps:"
echo ""
echo "1. Go to your Supabase project dashboard"
echo "2. Navigate to Settings → Database"
echo "3. In the 'Connection info' section, find 'Connection string'"
echo "4. Copy the SESSION POOLER connection string (NOT the direct connection)"
echo "5. It should look like:"
echo "   postgresql://postgres.vjlozlmvvvhcyfdqepuz:[YOUR-PASSWORD]@[POOLER-HOST]:6543/postgres"
echo ""
echo "6. Update your .env file with the values from that string:"
echo ""
echo "Current .env values:"
echo "PG_HOST=$(grep PG_HOST .env | cut -d'=' -f2)"
echo "PG_PORT=$(grep PG_PORT .env | cut -d'=' -f2)"
echo "PG_USER=$(grep PG_USER .env | cut -d'=' -f2)"
echo "PG_PASSWORD=$(grep PG_PASSWORD .env | cut -d'=' -f2)"
echo ""
echo "7. Alternative: Use the full connection string approach"
echo "   Create a DATABASE_URL in .env:"
echo "   DATABASE_URL=postgresql://postgres.vjlozlmvvvhcyfdqepuz:[PASSWORD]@[POOLER-HOST]:6543/postgres"
echo ""
echo "8. Test the connection:"
echo "   node test-all-connections.js"
echo ""
echo "Note: The hostname 'db.vjlozlmvvvhcyfdqepuz.supabase.co' is not resolving."
echo "This suggests it might be incorrect or the project might need activation."
